--gtk-version=4
--enable-global-vaapi-lock

--ignore-gpu-blocklist
--enable-zero-copy

--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,VaapiOnNvidiaGPUs,WaylandLinuxDrmSyncobj
# --disable-features=UseChromeOSDirectVideoDecoder

# --enable-features=VaapiVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE

