[colors.primary]
background = '#1e1e2e'
foreground = '#cdd6f4'

[colors.selection]
text = '#cdd6f4'
background = '#6f2438'

[colors.cursor]
text = '#1e1e2e'
cursor = '#f38ba8'

[colors.normal]
black   = '#181825'
red     = '#ff7277'
green   = '#97f379'
yellow  = '#ffe272'
blue    = '#e67091'
magenta = '#701830'
cyan    = '#f38ba8'
white   = '#ffeff3'

[colors.bright]
black   = '#9d9295'
red     = '#ff9fa2'
green   = '#bbffa5'
yellow  = '#ffeca5'
blue    = '#ffa2bc'
magenta = '#ffb2c7'
cyan    = '#ffcddb'
white   = '#fff8fa'
