[colors.primary]
background = '#1e1e2e'
foreground = '#cdd6f4'

[colors.selection]
text = '#cdd6f4'
background = '#6d3641'

[colors.cursor]
text = '#1e1e2e'
cursor = '#eba0ac'

[colors.normal]
black   = '#181825'
red     = '#ff7275'
green   = '#90eb75'
yellow  = '#ffe272'
blue    = '#df8997'
magenta = '#6c2d37'
cyan    = '#eba0ac'
white   = '#f6e7ea'

[colors.bright]
black   = '#988d8f'
red     = '#ff9fa1'
green   = '#baffa5'
yellow  = '#ffeda5'
blue    = '#ffb9c4'
magenta = '#ffc6cf'
cyan    = '#ffdae0'
white   = '#fff8f9'
