[colors.primary]
background = '#16161e'
foreground = '#a9b1d6'

[colors.selection]
text = '#a9b1d6'
background = '#2f334d'

[colors.cursor]
text = '#16161e'
cursor = '#7dcfff'

[colors.normal]
black   = '#1a1b26'
red     = '#ff709d'
green   = '#7dff8c'
yellow  = '#fff670'
blue    = '#5ebbf2'
magenta = '#074d76'
cyan    = '#7dcfff'
white   = '#eff9ff'

[colors.bright]
black   = '#474c50'
red     = '#ff9dbc'
green   = '#a4ffae'
yellow  = '#fff9a4'
blue    = '#90d6ff'
magenta = '#a4ddff'
cyan    = '#c4e9ff'
white   = '#f8fcff'
